Installer: Guard output redirection macOS/Linux

diff --git a/ant/apple/apple-preinstall.sh.in b/ant/apple/apple-preinstall.sh.in
--- a/ant/apple/apple-preinstall.sh.in
+++ b/ant/apple/apple-preinstall.sh.in
@@ -3,6 +3,12 @@
 # Halt on first error
 set -e
 
+# Prevent tampering
+if [ -L "${install.log}" ]; then
+    echo "ERROR: '$log_file' file appears tampered, aborting."
+    exit 1
+fi
+
 # Clear the log for writing
 > "${install.log}"
 
diff --git a/ant/linux/linux-installer.sh.in b/ant/linux/linux-installer.sh.in
--- a/ant/linux/linux-installer.sh.in
+++ b/ant/linux/linux-installer.sh.in
@@ -6,6 +6,12 @@ set -e
 TARGET_DIR="/opt/"
 LOG_FILE="${install.log}"
 
+# Prevent tampering
+if [ -L "${install.log}" ]; then
+    echo "ERROR: '$log_file' file appears tampered, aborting."
+    exit 1
+fi
+
 if [ "$(id -u)" != "0" ]; then
     if [ "$1" == "--user" ]; then
         TARGET_DIR="$HOME/.local/opt/"
